author:
  name: "Gavin Stewart"
  email: "gavin@gdks.co.uk"
  url: "https://gdks.github.io"

assets:
  compress:
      css: true
      js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md

ga_analytics: # Add Google Analytics tracking code

gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap

name: GDKS Blog

permalink: pretty

url: http://gdks.github.io

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
